# OllamaChatModelController类的simpleChat方法
GET http://localhost:8080/model/simple/chat

###
# OllamaChatModelController类的streamChat方法
GET http://localhost:8080/model/stream/chat

###
# OllamaChatModelController类的customChat方法
GET http://localhost:8080/model/custom/chat

###
# OllamaChatClientController类的simpleChat方法
GET http://localhost:8080/client/simple/chat

###
# OllamaChatClientController类的streamChat方法
GET http://localhost:8080/client/stream/chat
