# Nl2sqlForGraphController类的search方法
GET http://localhost:8065/nl2sql/search

###
# AnalyticNl2SqlController类的nl2Sql方法
POST http://localhost:8065/chat

###
# HomeController类的index方法
GET http://localhost:8065/

###
# HomeController类的index方法
POST http://localhost:8065/

###
# SimpleChatController类的simpleNl2Sql方法
POST http://localhost:8065/simpleChat
