spring:
  application:
    name: rag-pgvector-example

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: mysecretpassword

  ai:
    dashscope:
      api-key: ${DASH_SCOPE_API_KEY}
    vectorstore:
      pgvector:
        dimensions: 1536
        index-type: hnsw
        distance-type: cosine_distance
