services:
  nacos:
    image: nacos/nacos-server:v3.0.0
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=aB3dEfG7hIjKlmN9oPqRsTuVwXyZ12345
      - NACOS_AUTH_IDENTITY_VALUE=xYz9QwErTyUiOp12345678AbCdEfGh
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    volumes:
      - nacos-logs:/home/nacos/logs
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
volumes:
  nacos-logs: