server:
  port: 8080
minimax:
  memory:
    file: spring-ai-alibaba-chat-example/minimax-chat/memory/learning-memory.json
spring:
  application:
    name: minimax-chat-example
  ai:
    model:
      chat: openai
    openai:
      base-url: https://api.minimaxi.com
      api-key: ${MINIMAX_API_KEY}
      chat:
        options:
          model: MiniMax-M2.7
          temperature: 0.7
