server:
  port: 10006

spring:
  application:
    name: spring-ai-alibaba-ollama-chat-client-example

  ai:
    ollama:
      base-url: http://140.143.170.96:11434     # 替换为自己的地址
      chat:
        model: deepseek-r1:1.5b
