# VideoController类的textToVideo方法
GET http://localhost:10081/ai/video/text

###
# VideoController类的videoTmpl方法
GET http://localhost:10081/ai/video/tmpl

###
# VideoController类的firstFrame方法
GET http://localhost:10081/ai/video/first

###
# VideoController类的firstAndLastFrame方法
GET http://localhost:10081/ai/video/fl
