server:
  port: 8080

spring:
  application:
    name: redis-example

  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}

    vectorstore:
      redis:
        initialize-schema: true
        prefix: prefix_spring_ai_alibaba
        index: index_spring_ai_alibaba

  data:
    redis:
      host: localhost
      port: 6379 # Redis服务器连接端口