server:
  port: ${SERVER_PORT:21000}

spring:
  main:
    banner-mode: off
  application:
    name: nacos3-gateway-server
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 1.0.0
        enabled: true
        protocol: STREAMABLE
        type: ASYNC
        instructions: "This reactive server provides time information tools and resources"
        request-timeout: 20s
        streamable-http:
          mcp-endpoint: /mcp
          keep-alive-interval: 30s
          disallow-delete: false
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:${AI_DASHSCOPE_API_KEY:}}

    alibaba:
      mcp:
        gateway:
          enabled: true
          nacos:
            service-names: mcp-nacos-restful
        nacos:
          namespace: 0908ca08-c382-404c-9d96-37fe1628b183
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos

logging:
  level:
    com.alibaba.cloud.ai.mcp: DEBUG
