server:
  port: 19100

spring:
  application:
    name: mcp-annotation-client
  main:
    web-application-type: none
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:}
    mcp:
      client:
        enabled: true
        name: annotation-client
        version: 1.0.0
        request-timeout: 600s
        type: SYNC
        streamable-http:
          connections:
            annotation-server:
              url: http://localhost:18100
              endpoint: /mcp
        annotation-scanner:
          enabled: true
