# DeepSeekChatModelController类的simpleChat方法
GET http://localhost:8080/model/simple/chat

###
# DeepSeekChatModelController类的streamChat方法
GET http://localhost:8080/model/stream/chat

###
# DeepSeekChatClientController类的customOptions方法
GET http://localhost:8080/client/ai/customOptions

###
# DeepSeekChatClientController类的chat方法
GET http://localhost:8080/client/ai/generate

###
# DeepSeekChatClientController类的stream方法
GET http://localhost:8080/client/ai/stream
