server:
  port: 10091

spring:
  application:
    name: spring-ai-alibaba-text-summarizer-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}

  servlet:
    multipart:
      max-file-size: 5MB