server:
  port: 8848

spring:
  application:
    name: spring-ai-alibaba-multi-model-chat-example

  ai:
    ollama:
      chat:
        model: qwen2.5
        enabled: true

    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
