# Aduio Transcription API

### STT(speech to text) call API
GET http://127.0.0.1:10009/ai/transcription/call

### STT(speech to text) stream API
GET http://127.0.0.1:10009/ai/transcription/stream

# Audio Speech API

### TTS(text to speech) API
GET http://127.0.0.1:10009/ai/speech/call

### TTS(text to speech) stream API
GET http://127.0.0.1:10009/ai/speech/stream
